### PR TITLE
debugging

### PR DESCRIPTION
**Pull request by AkshathaAcharya55555**
debugging

### CODE REVIEW

**Comment by Accuracy-exe** [comment]
Hi @AkshathaAcharya55555 
Could you explain what was the bug that u fixed?

**Comment by AkshathaAcharya55555** [comment]
-  has_won flag:in the PLAYER struct: It indicates whether the player has
won.
-  position field: in the PLAYER struct: It stores the player's ranking.
-  Final Ranking: After the game ends, the program prints the rankings of
all players.

**Comment by Accuracy-exe** [comment]
Good work!

**Comment by Accuracy-exe** [comment]
!bounty 40

**Pull request closed without merging**
